### ISSUE TITLE
404 error when nagivating to https://openbadge-analysis.readthedocs.io.

### ISSUE THREAD

**Issue by jeremibourgault** [HumanDynamics/openbadge-analysis#19]
Dear contributors,

it appears that the links provided for the documentation is not working anymore :-/

Perhaps upload the content to Github?

Thanks

J

**Comment by OrenLederman** [comment]
There were never documentations for this package. The best way to learn about it is to look at the examples repo (https://github.com/HumanDynamics/openbadge-analysis-examples) or search the forum. I posted a comprehensive example about proximity analysis a while ago - https://groups.google.com/forum/#!topic/rhythm-badges/gSrMX_-KgnE
